### ISSUE TITLE
Fix Freya Node Functionality

### ISSUE THREAD

**Issue by AHBruns** [Topl/Bifrost#101]
Freya's node is not running correctly on startup making it unavailable for API calls. This is blocking for most Freya development.

**Comment by AHBruns** [comment]
Getting this error on node start-up:

stdout: 23:16:58.010| ERROR [H0pEFgwskD9aisHy-akka.actor.default-dispatcher-5] akka.actor.OneForOneStrategy - None.get
akka.actor.ActorInitializationException: akka://H0pEFgwskD9aisHy/user/$b: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at bifrost.state.BifrostState$.readOrGenerate(BifrostState.scala:824)
	at bifrost.BifrostNodeViewHolder.restoreState(BifrostNodeViewHolder.scala:50)
	at bifrost.scorexMod.GenericNodeViewHolder.$init$(GenericNodeViewHolder.scala:44)
	at bifrost.BifrostNodeViewHolder.<init>(BifrostNodeViewHolder.scala:22)
	at bifrost.BifrostApp.$anonfun$nodeViewHolderRef$1(BifrostApp.scala:41)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 common frames omitted

**Comment by yamir1995** [comment]
Node seems to be working fine on my machine. Alex is investigating issues with his Wifi that might be blocking the port required for the API requests.
