### ISSUE TITLE
[5pt] StackOverflowError when parsing blocks

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#180]
java.lang.StackOverflowError
	at scala.collection.mutable.ArrayOps.slice(ArrayOps.scala:47)
	at scala.collection.mutable.ArrayOps.slice$(ArrayOps.scala:44)
	at scala.collection.mutable.ArrayOps$ofByte.slice(ArrayOps.scala:206)
	at scala.collection.IndexedSeqOptimized.take(IndexedSeqOptimized.scala:137)
	at scala.collection.IndexedSeqOptimized.take$(IndexedSeqOptimized.scala:137)
	at scala.collection.mutable.ArrayOps$ofByte.take(ArrayOps.scala:206)
	at bifrost.blocks.BifrostBlockCompanion$.$anonfun$parseBytes2xAndBefore$3(BifrostBlock.scala:258)
	at bifrost.blocks.BifrostBlockCompanion$.unfoldLeft$2(BifrostBlock.scala:247)
	at bifrost.blocks.BifrostBlockCompanion$.unfoldLeft$2(BifrostBlock.scala:248)
	at bifrost.blocks.BifrostBlockCompanion$.unfoldLeft$2(BifrostBlock.scala:248)
...

The unfoldLeft function is a recursive call that quickly overflows on a large chain. A possible fix is to change unfoldLeft to be tail recursive.

**Comment by Tuxman** [comment]
Changed unfoldLeft to be tail recursive, now there is an issue with parsing transactions from storage. 


Failure(scala.MatchError: sferTransaction (of class java.lang.String))
ls.length: 2
typeStr: ArbitTransfer
blockId: CiFC6Pu1CZAmwezXRsj58DPFC7N3DtBdGU3LVzzPTeqX height: 1
bytes.head: 3
10:34:54.588| WARN  [B9hlmFgHdlzC9LZ7-akka.actor.default-dispatcher-3] bifrost.history.BifrostStorage - Failed to parse bytes from db
scala.MatchError: ArbitTransfer (of class java.lang.String)
	at bifrost.transaction.serialization.BifrostTransactionCompanion$.$anonfun$parseBytes$1(BifrostTransactionCompanion.scala:25)
	at scala.util.Try$.apply(Try.scala:209)
	at bifrost.transaction.serialization.BifrostTransactionCompanion$.parseBytes(BifrostTransactionCompanion.scala:19)
	at bifrost.blocks.BifrostBlockCompanion$.$anonfun$parseBytes$5(BifrostBlock.scala:219)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.immutable.List.map(List.scala:294)
	at bifrost.blocks.BifrostBlockCompanion$.$anonfun$parseBytes$1(BifrostBlock.scala:219)
	at scala.util.Try$.apply(Try.scala:209)
	at bifrost.blocks.BifrostBlockCompanion$.parseBytes(BifrostBlock.scala:166)
	at bifrost.history.BifrostStorage.$anonfun$modifierById$1(BifrostStorage.scala:45)
	at scala.Option.flatMap(Option.scala:171)
	at bifrost.history.BifrostStorage.modifierById(BifrostStorage.scala:38)
	at bifrost.history.BifrostStorage.bestBlock(BifrostStorage.scala:32)
	at bifrost.history.BifrostHistory.bestBlock$lzycompute(BifrostHistory.scala:50)
	at bifrost.history.BifrostHistory.bestBlock(BifrostHistory.scala:50)
	at bifrost.history.BifrostHistory.syncInfo(BifrostHistory.scala:228)
	at bifrost.history.BifrostHistory.syncInfo(BifrostHistory.scala:32)
	at bifrost.scorexMod.GenericNodeViewHolder$$anonfun$getSyncInfo$1.applyOrElse(GenericNodeViewHolder.scala:264)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at bifrost.BifrostNodeViewHolder.aroundReceive(BifrostNodeViewHolder.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
