### ISSUE TITLE
Receiving partial message failures using `2.0.0-beta4-2-8c7bea8f`

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#3252]
Updated container image to the latest `dev` version and I am receiving JVM error messages about input message ending unexpectedly
```
java.lang.IllegalArgumentException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at co.topl.networking.blockchain.BlockchainSocketHandler.tDecoded(BlockchainSocketHandler.scala:365)
        at co.topl.networking.blockchain.BlockchainSocketHandler.$anonfun$processRequest$2(BlockchainSocketHandler.scala:218)
        at getOrElseF @ co.topl.algebras.StoreReader.getOrRaise(Store.scala:14)
        at flatMap @ co.topl.networking.blockchain.BlockchainSocketHandler.processRequest(BlockchainSocketHandler.scala:208)
```

A partial log showing the application startup is included below
[20240730-bifrost_startup.txt](https://github.com/user-attachments/files/16431496/20240730-bifrost_startup.txt)

**Comment by admiraladmirable** [comment]
@scasplte2 We identified a bug in the p2p fs2 code in `Socket#read` that seems to appear in cases that cross physical network boundaries.

It is prioritized to be fixed this sprint. I'll link the PR when that's implemented.

**Comment by admiraladmirable** [comment]
@scasplte2 https://github.com/Topl/Bifrost/pull/3253 was merged which may help with your issue. It is deployed to `devnet.apparatusnetwork.xyz:443`. Let me know if you can connect to that network and if it solves your issue.

**Comment by scasplte2** [comment]
Thanks @admiraladmirable, just a note that I had to add the `--disableGenus` flag as when I used the above args then my docker service crashed and the machine had to be restarted. The node is up and bootstrapping now so I will report back. 

On a separate note, if I wanted to configure Genus for indexing, are there docs I could look at?

**Comment by scasplte2** [comment]
Also, this is probably known but just for the sake of documenting, here is the network usage while bootstrapping. There is plenty of headroom on the interface so this is just what the application is demanding.
![image](https://github.com/user-attachments/assets/eb4e9b95-3715-4d50-b6dc-2396a5b3ae8c)

**Comment by admiraladmirable** [comment]
> Thanks @admiraladmirable, just a note that I had to add the `--disableGenus` flag as when I used the above args then my docker service crashed and the machine had to be restarted. The node is up and bootstrapping now so I will report back.

Do you have any CPU/memory limits defined for your Docker setup? We _generously_ give the standalone Genus instance 4GB of memory (used to be higher until some optimizations went through).

> On a separate note, if I wanted to configure Genus for indexing, are there docs I could look at?

I didn't find it in our docs, we definitely need to take another pass at those. An example of configuring genus to replicate against `devnet`.
```
docker run --rm toplprotocol/genus:2.0.0-beta5 --nodeRpcHost devnet.apparatusnetwork.xyz --nodeRpcPort 443 --nodeRpcTls true --orientDbPassword admin --dataDir /tmp/genus/ --enableReplicator true
```

You'd probably want to target your local relay node though, in which case you would use something like:

```
docker run --rm toplprotocol/genus:2.0.0-beta5 --nodeRpcHost <docker-bifrost-dns-name> --nodeRpcPort <docker-bifrost-port> --nodeRpcTls false --orientDbPassword admin --dataDir /tmp/genus/ --enableReplicator true
```

**Comment by scasplte2** [comment]
Alright @admiraladmirable got some new odd behavior when attempting to bootstrap with the latest version. Once my node establishes a connection, I am able to download block data for approx. 6 minutes after which I encounter an TimeoutException error that the common ancestor trace took too long. After another three minutes or so the peer connection is reestablished and my node begins to download block data once again. The error occurs consistently and so far seems to have happened about 15 times (from the counter on number of times the peer connection has been closed).

From gRPC I can see that my chain height is progressing (via Fetch Id at height and manually incrementing the queried height) so the download seems to be resuming from where it left off. I also measured that the block interval between failures seems to be around 3000 as I had errors at the following heights (36593, 39547, 42742). That is just a partial list, but might at least rule out some fixed block size cache or boundary crossing.

Below are partial logs of the error I am encountering and the reconnection to the peer that resumes downloading.
---
Error logs
```
15:26:58.894| INFO  Bifrost.P2P - Download 0 txs from 4VcEx7n2... for block b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t
15:26:58.894| INFO  Bifrost.P2P - Download next bodies: b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t with res true
15:26:58.894| INFO  Bifrost.P2P - Send bodies prefix to block checker List(BlockHeader(id=b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t parentId=b_9oZphsYLKxuqG5998Ain22SAnXprVSrGaoV91ujf1AzR parentSlot=228347 timestamp=2024-03-23T11:48:52.814Z height=33418 slot=228353 address=BsVvuo3e79Ra8W5R93maT28LgvRFXcrYbCLi9wxNuZeB))
15:26:58.894| INFO  Bifrost.P2P - Start processing bodies for ids: NonEmptyChain(b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t)
15:26:58.894| INFO  Bifrost.P2P - Start processing new block body b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t
15:26:58.895| INFO  Bifrost.P2P - Verified body b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t duration=0ms
15:26:58.895| INFO  Bifrost.P2P - Compare local chain after block apply duration=0ms
15:26:58.896| INFO  Bifrost.LocalChain - Adopted head block id=b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t height=33418 slot=228353
15:26:58.896| INFO  Bifrost.P2P - Successfully adopted block: b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t
15:26:58.896| INFO  Bifrost.P2P - Successfully process body: b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t
15:26:58.902| INFO  Bifrost.P2P - Get missed bodies duration=5ms
15:26:58.902| INFO  Bifrost.P2P - Send request to get bodies for: NonEmptyChain(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:26:58.902| INFO  Bifrost.P2P - Get request for bodies downloads NonEmptyChain(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:26:58.902| INFO  Bifrost.P2P - Send already downloaded bodies to block checker List()
15:26:58.902| INFO  Bifrost.P2P - Send request for additional block body download List(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:26:58.931| INFO  Bifrost.P2P - Fetched header b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y: BlockHeader(id=b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y parentId=b_126TrkYUTYRrnZFM52joxjTuwTExZhNrhMqhgMXMVyUq parentSlot=228435 timestamp=2024-03-23T11:50:23.180Z height=33431 slot=228443 address=FRgUuiRqxeiZa1yuy2KXex4uDXHBGFFKcghXyoXK31sQ) from 4VcEx7n2... for 90 ms
15:26:58.931| INFO  Bifrost.P2P - Associating child=b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y to parent=b_126TrkYUTYRrnZFM52joxjTuwTExZhNrhMqhgMXMVyUq
15:26:58.931| INFO  Bifrost.P2P - Download next headers: b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y with res true
15:26:58.932| INFO  Bifrost.P2P - Received header download from host 4VcEx7n2... with delay 90 ms
15:26:58.932| INFO  Bifrost.P2P - Send headers prefix to block checker List(b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y)
15:26:58.932| INFO  Bifrost.P2P - Start processing headers: NonEmptyChain(UnverifiedBlockHeader(id=b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y, source=4VcEx7n2..., downloadTime=90 ms))
15:26:58.932| INFO  Bifrost.P2P - Start processing new header b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y
15:26:58.932| INFO  Bifrost.P2P - Get missed bodies duration=0ms
15:26:58.935| INFO  Bifrost.P2P - Verified header b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y duration=2ms
15:26:58.935| INFO  Bifrost.P2P - Successfully process header: b_A3YN2kr5zKtYiHC9TEuSEidW4GZ8HR8KPpZYSeqnMa5Y
15:26:58.941| INFO  Bifrost.P2P - Find N-missing header duration=0ms
15:26:58.941| INFO  Bifrost.P2P - Send request to get missed headers for blockIds: NonEmptyChain(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:26:58.942| INFO  Bifrost.P2P - Request next headers total time duration=6ms
15:26:58.942| INFO  Bifrost.P2P - Get request for headers downloads NonEmptyChain(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:26:58.942| INFO  Bifrost.P2P - Send already downloaded header to block checker List()
15:26:58.942| INFO  Bifrost.P2P - Send request for additional block header download List(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:26:58.942| INFO  Bifrost.P2P - Send request to get bodies for: NonEmptyChain(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:26:58.942| INFO  Bifrost.P2P - Forward to 4VcEx7n2... download block header(s) NonEmptyChain(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:26:58.942| INFO  Bifrost.P2P - Get request for bodies downloads NonEmptyChain(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:26:58.942| INFO  Bifrost.P2P - Send already downloaded bodies to block checker List()
15:26:58.942| INFO  Bifrost.P2P - Send request for additional block body download List()
15:27:01.931| ERROR Bifrost.P2P - Common ancestor trace for peer 4VcEx7n2... is failed because java.util.concurrent.TimeoutException: 3 seconds
15:27:01.932| ERROR Bifrost.P2P - Got non critical error from host 4VcEx7n2...
15:27:01.932| INFO  Bifrost.P2P - Going to stop network and application level for peers Set(4VcEx7n2...)
15:27:01.932| INFO  Bifrost.P2P - Move 4VcEx7n2... from HOT to COLD
15:27:04.932| ERROR Bifrost.P2P - Error java.util.concurrent.TimeoutException: 3 seconds during getting remote peer(s) neighbours
15:27:04.932| ERROR Bifrost.P2P - Failed download block b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW from peer 4VcEx7n2... because of: Unknown error during getting header from peer due next throwable java.util.concurrent.TimeoutException: 3 seconds
15:27:04.932| ERROR Bifrost.P2P - Failed download block b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc from peer 4VcEx7n2... because of: Unknown error during getting block from peer due next throwable java.util.concurrent.TimeoutException: 3 seconds
15:27:04.932| ERROR Bifrost.P2P - Got non critical error from host 4VcEx7n2...
15:27:04.932| INFO  Bifrost.P2P - Download next bodies: b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc with res false
15:27:04.932| INFO  Bifrost.P2P - Going to stop network and application level for peers Set(4VcEx7n2...)
15:27:04.932| INFO  Bifrost.P2P - Send bodies prefix to block checker List()
15:27:04.932| INFO  Bifrost.P2P - Application level is disabled for 4VcEx7n2...
15:27:04.933| INFO  Bifrost.P2P - Download next headers: b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW with res false
15:27:04.933| INFO  Bifrost.P2P - Stop block header fetcher fiber for peer 4VcEx7n2...
15:27:04.933| INFO  Bifrost.P2P - Send headers prefix to block checker List()
15:27:04.933| INFO  Bifrost.P2P - Move 4VcEx7n2... from COLD to COLD
15:27:04.933| INFO  Bifrost.P2P - Stop mempool sync fiber for peer 4VcEx7n2...
15:27:04.933| ERROR Bifrost.P2P - Got non critical error from host 4VcEx7n2...
15:27:04.933| INFO  Bifrost.P2P - Going to stop network and application level for peers Set(4VcEx7n2...)
15:27:04.933| INFO  Bifrost.P2P - Stop body fetcher actor for peer 4VcEx7n2...
15:27:04.933| INFO  Bifrost.P2P - Move 4VcEx7n2... from COLD to COLD
15:27:04.933| ERROR Bifrost.P2P - Failed to get source host for getting body(s) List(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:27:04.933| ERROR Bifrost.P2P - Clean current best chain due error in receiving/validation data from NonEmptyChain(b_2Nt3Dk6AFbQnAYwnQsK81bM8b8q5ubDwzN2tnpwEfcUc)
15:27:04.933| ERROR Bifrost.P2P - Got non critical error from host 4VcEx7n2...
15:27:04.933| INFO  Bifrost.P2P - Reset request proxy
15:27:04.933| INFO  Bifrost.P2P - Going to stop network and application level for peers Set(4VcEx7n2...)
15:27:04.933| INFO  Bifrost.P2P - Move 4VcEx7n2... from COLD to COLD
15:27:04.933| ERROR Bifrost.P2P - Failed to get source host for getting header(s) NonEmptyChain(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:27:04.934| INFO  Bifrost.P2P - Got request to get all available tips
15:27:04.934| ERROR Bifrost.P2P - Clean current best chain due error in receiving/validation data from NonEmptyChain(b_97d83B33wH96qwbRhktgvrBNp4SKsqgbZVDgJKeBuYoW)
15:27:04.934| INFO  Bifrost.P2P - Reset request proxy
15:27:04.934| INFO  Bifrost.P2P - Got request to get all available tips
15:27:07.933| INFO  Bifrost.P2P - Run finalizer for actor for peer 4VcEx7n2...
15:27:08.853| INFO  Bifrost.P2P - This peer id: 8ojpNJLP...
15:27:08.853| INFO  Bifrost.P2P - Known local addresses: Set(192.168.86.3)
15:27:08.853| INFO  Bifrost.P2P - 8ojpNJLP...: Current (0) hot peer(s) state: Map()
15:27:08.854| INFO  Bifrost.P2P - Hot peers sum for 8ojpNJLP...: 
15:27:08.854| INFO  Bifrost.P2P - Current (0) warm peer(s) state: Map()
15:27:08.854| INFO  Bifrost.P2P - Current first five of (1) cold peer(s) state: Map(4VcEx7n2... -> <<< Peer Connected address=35.226.130.231:9085; Server address=RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085); State=Cold; Actor=absent; Remote peer=no active; Rep: block=0.00, perf=0.00, new=0, mean=0.00; With total 14 closes with last close 2024-08-12T20:27:01.932Z; >>>)
15:27:08.854| INFO  Bifrost.P2P - With known cold peers: Map(4VcEx7n2... -> Some(RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085)))
15:27:08.854| INFO  Bifrost.P2P - BlockChecker queue size: Some(0)
15:27:08.854| INFO  Bifrost.P2P - PeersManager queue size: Some(0)
15:27:08.854| INFO  Bifrost.P2P - Requests proxy queue size: Some(0)
15:27:10.934| INFO  Bifrost.P2P - Ignoring stopping mempool sync fetcher fiber for peer 4VcEx7n2...
15:27:10.934| INFO  Bifrost.P2P - Stop body fetcher actor for peer 4VcEx7n2...
15:27:10.934| INFO  Bifrost.P2P - Ignoring stopping block header fetcher fiber for peer 4VcEx7n2...
15:27:10.934| INFO  Bifrost.P2P - Peer Actor for peer 4VcEx7n2...: is released
15:27:10.935| INFO  Bifrost.P2P - Remote peer 4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH complete
java.util.concurrent.TimeoutException: 3 seconds
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
        at main$ @ co.topl.common.application.IOBaseApp$$anon$1.main(IOBaseApp.scala:45)
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
java.util.concurrent.TimeoutException: 3 seconds
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
        at main$ @ co.topl.common.application.IOBaseApp$$anon$1.main(IOBaseApp.scala:45)
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
        at timeout$extension @ org.http4s.ember.client.internal.ClientHelpers$.writeRead$1(ClientHelpers.scala:168)
15:27:10.936| INFO  Bifrost.P2P - Remote peer 35.226.130.231:9085 closing had been detected
15:27:10.936| INFO  Bifrost.P2P - Connection closed with peer=DisconnectedPeer(address=35.226.130.231:9085, id=4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH)
15:27:10.936| INFO  Bifrost.P2P - Going to clean-up peer actor for Set(4VcEx7n2...) due to closed connection
15:27:10.937| INFO  Bifrost.P2P - Going to stop network and application level for peers Set(4VcEx7n2...)
15:27:10.937| INFO  Bifrost.P2P - Move 4VcEx7n2... from COLD to COLD
```
---
Reconnection logs
```
15:30:08.854| INFO  Bifrost.P2P - Current (0) warm peer(s) state: Map()
15:30:08.854| INFO  Bifrost.P2P - Current first five of (1) cold peer(s) state: Map(4VcEx7n2... -> <<< Peer Connected address=35.226.130.231:9085; Server address=RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085); State=Cold; Actor=absent; Remote peer=no active; Rep: block=0.00, perf=0.00, new=0, mean=0.00; With total 14 closes with last close 2024-08-12T20:27:01.932Z; >>>)
15:30:08.854| INFO  Bifrost.P2P - With known cold peers: Map(4VcEx7n2... -> Some(RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085)))
15:30:08.854| INFO  Bifrost.P2P - BlockChecker queue size: Some(0)
15:30:08.854| INFO  Bifrost.P2P - PeersManager queue size: Some(0)
15:30:08.854| INFO  Bifrost.P2P - Requests proxy queue size: Some(0)
15:30:18.847| INFO  Bifrost.P2P - Going to warm next cold peers: Set(4VcEx7n2...)
15:30:18.847| INFO  Bifrost.P2P - Move 4VcEx7n2... from COLD to WARM
15:30:18.848| INFO  Bifrost.P2P - Going to open connection to next peers: Vector(RemotePeer(id=4VcEx7n2... address=35.226.130.231:9085))
15:30:18.848| INFO  Bifrost.P2P - Outbound connection initializing with peer=35.226.130.231:9085
15:30:18.849| INFO  Bifrost.P2P - Initiate connection to DisconnectedPeer(address=35.226.130.231:9085, id=4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH)
15:30:18.853| INFO  Bifrost.P2P - This peer id: 8ojpNJLP...
15:30:18.853| INFO  Bifrost.P2P - Known local addresses: Set(192.168.86.3)
15:30:18.853| INFO  Bifrost.P2P - 8ojpNJLP...: Current (0) hot peer(s) state: Map()
15:30:18.853| INFO  Bifrost.P2P - Hot peers sum for 8ojpNJLP...: 
15:30:18.854| INFO  Bifrost.P2P - Current (1) warm peer(s) state: Map(4VcEx7n2... -> <<< Peer Connected address=35.226.130.231:9085; Server address=RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085); State=Warm; Actor=absent; Remote peer=no active; Rep: block=0.00, perf=0.00, new=0, mean=0.00; With total 14 closes with last close 2024-08-12T20:27:01.932Z; >>>)
15:30:18.854| INFO  Bifrost.P2P - Current first five of (0) cold peer(s) state: Map()
15:30:18.854| INFO  Bifrost.P2P - With known cold peers: Map()
15:30:18.854| INFO  Bifrost.P2P - BlockChecker queue size: Some(0)
15:30:18.854| INFO  Bifrost.P2P - PeersManager queue size: Some(0)
15:30:18.854| INFO  Bifrost.P2P - Requests proxy queue size: Some(0)
15:30:18.993| INFO  Bifrost.P2P - Established connection to DisconnectedPeer(address=35.226.130.231:9085, id=4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH)
15:30:18.993| INFO  Bifrost.P2P - Added 192.168.86.3 as known local address
15:30:18.993| INFO  Bifrost.P2P - Connection established local[192.168.86.3:40130] <=> remote[ConnectedPeer(address=35.226.130.231:9085, id=4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH, version=11111112)]
15:30:19.103| INFO  Bifrost.P2P - Going to create actor for handling connection to remote peer 4VcEx7n2...
15:30:19.206| INFO  Bifrost.P2P - Received remote peer as server Some(RemotePeer(id=4VcEx7n2... address=devnet.topl.co:9085)) from 4VcEx7n2...
15:30:19.286| INFO  Bifrost.P2P - Got pong message delay 79 ms from remote host 4VcEx7n2...
15:30:19.322| INFO  Bifrost.P2P - Network level is started for 4VcEx7n2...
15:30:19.360| INFO  Bifrost.P2P - Got pong message delay 38 ms from remote host 4VcEx7n2...
15:30:19.847| INFO  Bifrost.P2P - Going to hot next hosts: Set(4VcEx7n2...)
15:30:19.847| INFO  Bifrost.P2P - Move 4VcEx7n2... from WARM to HOT
15:30:19.848| INFO  Bifrost.P2P - Application level is enabled for 4VcEx7n2...
15:30:19.848| INFO  Bifrost.P2P - Start block header actor for peer 4VcEx7n2...
15:30:19.848| INFO  Bifrost.P2P - Start mempool sync actor for peer 4VcEx7n2...
15:30:19.848| INFO  Bifrost.P2P - Start body fetcher actor for peer 4VcEx7n2...
15:30:19.849| INFO  Bifrost.P2P - Fetching SlotData id=b_9pexZupxUz94s59sHVCDdAVEMCmgpQs4XWHMZNd5b8vA from peer 4VcEx7n2...
15:30:19.884| INFO  Bifrost.P2P - Got blockId: b_9pexZupxUz94s59sHVCDdAVEMCmgpQs4XWHMZNd5b8vA from peer 4VcEx7n2...
15:30:20.063| INFO  Bifrost.P2P - Remote peer ConnectedPeer(address=35.226.130.231:9085, id=4VcEx7n2anGTqTuBGRamjcEE2tvhKkCfDWS1ZLaug8eH, version=11111112) application level is true
15:30:20.063| INFO  Bifrost.P2P - Update remote network level for peer 4VcEx7n2... to true
15:30:20.592| INFO  Bifrost.P2P - For slot b_9pexZupxUz94s59sHVCDdAVEMCmgpQs4XWHMZNd5b8vA with height 1752876 from peer 4VcEx7n2... : commonSlotHeight=33418, requestedHeight=38602
15:30:20.735| INFO  Bifrost.P2P - Sync slot data sync chain b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t:b_8BARGk99oJw4jDN4dfisXpx5o6KDmXVT324KXzYzXvbS from peer 4VcEx7n2... for b_9pexZupxUz94s59sHVCDdAVEMCmgpQs4XWHMZNd5b8vA
15:30:20.735| INFO  Bifrost.P2P - Slot data chain download request b_4DFPpZ9kj4j4AFmEGF6PxFB6dW4D4rqfBvyq5iM6vS9t with height 33418 : b_8BARGk99oJw4jDN4dfisXpx5o6KDmXVT324KXzYzXvbS with height 38602 from peer 4VcEx7n2...
15:30:20.891| INFO  Bifrost.P2P - Got no hot peers from 4VcEx7n2...
```

**Comment by admiraladmirable** [comment]
@scasplte2 Thanks, I'll bring it up with the team.

**Comment by admiraladmirable** [comment]
@scasplte2 are you still seeing this behavior? I've made a few changes on the networking side of things and validated that I can sync to devnet:

```
docker run --rm toplprotocol/bifrost-node:2.0.0-beta5 --disableGenus --knownPeers devnet.apparatusnetwork.xyz:9085 --config https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3/config.yaml
```

One thing to note is that `2.0.0-beta5` is semi breaking where:
* `beta4` -> `beta5` connects
* `beta5` -> `beta4` does not connect

I'll circle back when testnet and mainnet are updated to `beta5`.

**Comment by scasplte2** [comment]
> @scasplte2 are you still seeing this behavior? I've made a few changes on the networking side of things and validated that I can sync to devnet:
> 
> ```
> docker run --rm toplprotocol/bifrost-node:2.0.0-beta5 --disableGenus --knownPeers devnet.apparatusnetwork.xyz:9085 --config https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3/config.yaml
> ```
> 
> One thing to note is that `2.0.0-beta5` is semi breaking where:
> 
> * `beta4` -> `beta5` connects
> * `beta5` -> `beta4` does not connect
> 
> I'll circle back when testnet and mainnet are updated to `beta5`.

@admiraladmirable Seems like things are as expected now 🎉 Been syncing for the the last 30 minutes or so without interruption

**Comment by scasplte2** [comment]
closing since this seems to be resolved now
