### ISSUE TITLE
[1pt] Next on empty iterator error

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#368]
After syncing, a query node returns this periodically when receiving a new block.

```
ERROR [YHFuB8YfX77VpZTc-akka.actor.default-dispatcher-2] akka.actoOneStrategy - next on empty iterator
l.NoSuchElementException: next on empty iterator
at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
at scala.collection.IterableLike.head(IterableLike.scala:109)
at scala.collection.IterableLike.head$(IterableLike.scala:108)
at scala.collection.AbstractIterable.head(Iterable.scala:56)
at bifrost.forging.Forger.to$lzycompute$1(Forger.scala:60)
at bifrost.forging.Forger.to$1(Forger.scala:60)
at bifrost.forging.Forger.CB$lzycompute$1(Forger.scala:63)
at bifrost.forging.Forger.CB$1(Forger.scala:63)
at bifrost.forging.Forger.$anonfun$pickTransactions$1(Forger.scala:64)
at scala.util.Try$.apply(Try.scala:213)
at bifrost.forging.Forger.pickTransactions(Forger.scala:58)
at bifrost.forging.Forger$$anonfun$receive$1.applyOrElse(Forger.scala:11
at akka.actor.Actor.aroundReceive(Actor.scala:539)
at akka.actor.Actor.aroundReceive$(Actor.scala:537)
at bifrost.forging.Forger.aroundReceive(Forger.scala:35)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
at akka.actor.ActorCell.invoke(ActorCell.scala:581)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
at akka.dispatch.Mailbox.run(Mailbox.scala:229)
at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.ja
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.)
```

**Comment by Tuxman** [comment]
Once synced, query nodes were still forging. When a node checks with at least 1 other node and finds noBetterNeighbor, the Forger is sent a startForging message. Adding a harder disable value to the settings for the forger makes sure that if offlineGeneration is set to false, the node will not start forging after becoming synced to other nodes.
